protected/controllers/FormController.php
<?php

class FormController extends Controller
{
	public function actionIndex()
	{

        $models = UserForm::model()->findAll();

		$this->render('index', [
            "models" => $models
        ]);
	}

    public function actionCreate()
	{
        $model = new SearchPreviewForm();
        $colorSchemeAttributes = self::getColorSchemeAttributes();

        if(isset($_POST["SearchPreviewForm"])){

            $model->setAttributes($_POST['SearchPreviewForm'], false);

            if(!$model->validate()){
                $this->render('create', [
                    "model" => $model,
                    "colorSchemeAttributes" => $colorSchemeAttributes
                ]);
            }

            $userForm = new UserForm();
            $userForm->title = $model->title;
            $userForm->created_at = date("Y-m-d");
            $userForm->id_user = 1;
            $userForm->data = $json = json_encode($model);
            $userForm->save();

            /*redirect to update page*/
            $this->redirect(["/form/update","id" => $userForm->id]);
        }

		$this->render('create', [
            "model" => $model,
            "colorSchemeAttributes" => $colorSchemeAttributes
        ]);
	}

    public function actionUpdate($id)
	{
        $model = new SearchPreviewForm();
        $colorSchemeAttributes = self::getColorSchemeAttributes();

        if(!$userForm = UserForm::model()->findByPk($id)){
            $this->render('create', [
                "model" => $model
            ]);
        }

        if(isset($_POST["SearchPreviewForm"])){

            $model->setAttributes($_POST['SearchPreviewForm'], false);

            if(!$model->validate()){
                $this->render('create', [
                    "model" => $model,
                    "colorSchemeAttributes" => $colorSchemeAttributes
                ]);
            }

            $userForm->title = $model->title;
            $userForm->data = $json = json_encode($model);
            $userForm->save();
        }

        $model->setAttributes(json_decode($userForm->data, true), false);
        $model->id = $userForm->id;
        $model->width = $model->width + 2;

		$this->render('update', [
            "model" => $model,
            "colorSchemeAttributes" => $colorSchemeAttributes
        ]);
	}

    public function actionDelete($id)
	{

        //todo make POST request instead GET

        if(!isset($id)){
            $this->redirect(["/form/index"]);
        }
        if(!$userForm = UserForm::model()->findByPk((int)$id)){
            $this->redirect(["/form/index"]);
        }

        $userForm->delete();

        $this->redirect(["/form/index"]);
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/

    public static function getColorSchemeAttributes(){
        return [
            "colorSchemeIcon" => new ColorSchemeAttribute("Icons","colorSchemeIcon", "formIcon", "color"),
            "colorSchemeText" => new ColorSchemeAttribute("Text","colorSchemeText", "formText", "color"),
            "colorSchemeBackground" => new ColorSchemeAttribute("Background","colorSchemeBackground", "formBackground", "background-color"),
            "colorSchemeBorder" => new ColorSchemeAttribute("Border","colorSchemeBorder", "formBorder", "border-color"),
            "colorSchemeButton" => new ColorSchemeAttribute("Button","colorSchemeButton", "formButton", "background-color"),
            "colorSchemeButtonText" => new ColorSchemeAttribute("Button text","colorSchemeButtonText", "formButtonText", "color"),
            "colorSchemeInputBorder" => new ColorSchemeAttribute("Input border","colorSchemeInputBorder", "formInput", "border-color")
        ];
    }

    public function actionCode(){

        $id = (int)$_POST["id"];

        if(!$userForm = UserForm::model()->findByPk($id)){
            echo json_encode([
                "errors" => 1,
                "errorMessage" => "Form not found"
            ]);return;
        }


        $result = '<script>
        var hash = "xGTZPJpsLPvNHcm2B";
        (function(d, w) {
            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script");
            w[c] = w[c] || function() {
                (w[c].q = w[c].q || []).push(arguments);
            };
            s.async = true;
            s.src = (d.location.protocol === "https:" ? "https:": "http:")
                + "//localhost.agentsky.dev/js/SearchPreviewForm.js";
            n.parentNode.insertBefore(s, n);
        })(document, window, "AgentSky");
    </script>';

        $result = '<script type="text/javascript" src="http://'.$_SERVER["HTTP_HOST"].'/?r=widget"></script>';

        echo json_encode([
            "errors" => 0,
            "code" => $result
        ]);return;
    }
}

protected/views/form/_color-schemes.php
<?php
/**
 * Created by PhpStorm.
 * User: A&A
 * Date: 4/21/16
 * Time: 11:29 PM
 * @var $colorSchemeAttributes array
 * @var $colorSchemeAttribute ColorSchemeAttribute
 */
?>

<?php $firstColor = "#fff"; $secondColor = "#CA4781"?><!-- WHITE / DARK RED -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeWhiteDarkred.png" /></div>

<?php $firstColor = "#fff"; $secondColor = "#000"?><!-- WHITE / BLACK -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeWhiteBlack.png"/></div>

<?php $firstColor = "#fff"; $secondColor = "#0ebcf2"?><!-- WHITE / BLUE -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeWhiteBlue.png" /></div>

<?php $firstColor = "#fff"; $secondColor = "#35a954"?><!-- WHITE / GREEN -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeWhiteGreen.png" /></div>

<?php $firstColor = "#CA4781"; $secondColor = "#FFF"?><!-- DARK RED / WHITE -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeDarkredWhite.png" /></div>

<?php $firstColor = "#000"; $secondColor = "#FFF"?><!-- BLACK / WHITE -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeBlackWhite.png" /></div>

<?php $firstColor = "#0ebcf2"; $secondColor = "#fff"?><!-- BLUE / WHITE -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeBlueWhite.png" /></div>

<?php $firstColor = "#35a954"; $secondColor = "#fff"?><!-- GREEN / WHITE -->
<?php $colorSchemeAttributes["colorSchemeIcon"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeText"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButton"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeButtonText"]->value = $firstColor;?>
<?php $colorSchemeAttributes["colorSchemeInputBorder"]->value = $secondColor;?>
<?php $colorSchemeAttributes["colorSchemeBackground"]->value = $firstColor;?>
<div class="color-scheme-icon" onclick="$('.color-scheme-icon').removeClass('active'); $(this).addClass('active');changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>);" ><img src="/images/color-schemes/colorSchemeGreenWhite.png" /></div>

protected/views/form/_custom-color-scheme.php
<?php
/**
 * Created by PhpStorm.
 * User: A&A
 * Date: 4/15/16
 * Time: 7:19 PM
 * @var $model SearchForm
 *  @var $colorSchemeAttributes array
 *  @var $colorSchemeAttribute ColorSchemeAttribute
 */
?>

<div class="display-none custom-scheme"><!--add class popup to hide on body click-->

    <h3>
        Custom color scheme
        <button class="btn btn-xs float-right" onclick="$(this).parent().parent().toggleClass('display-none'); return false;">X</button>
    </h3>
    <ul class="nav nav-pills nav-stacked col-md-4 custom-scheme-pills">
        <?php foreach ($colorSchemeAttributes as $colorSchemeAttribute):?>
            <li class="position-relative first-active">
                <a href="#<?=$colorSchemeAttribute->inputName?>Ref" data-toggle="pill"><?=$colorSchemeAttribute->title?></a>
                <div id="<?=$colorSchemeAttribute->inputName?>Preview" style="background-color: <?=$model->{$colorSchemeAttribute->inputName}?>"></div>
            </li>
        <?php endforeach;?>
    </ul>
    <div class="tab-content col-md-8">

        <?php foreach ($colorSchemeAttributes as $colorSchemeAttribute):?>
            <div class="tab-pane position-relative text-center first-active" id="<?=$colorSchemeAttribute->inputName?>Ref">
                <input id="<?=$colorSchemeAttribute->inputName?>Picker"
                    data-form-class="<?=$colorSchemeAttribute->formClass?>"
                    data-css-attribute="<?=$colorSchemeAttribute->cssAttribute?>"
                    data-preview="<?=$colorSchemeAttribute->inputName?>Preview"
                    data-input="<?=$colorSchemeAttribute->inputName?>Input"
                    class="colorPicker" value="<?=$model->{$colorSchemeAttribute->inputName} ?>"/>
            </div>
        <?php endforeach;?>



    </div>
</div>

protected/views/form/_form.php
<?php
/**
 * Created by PhpStorm.
 * User: A&A
 * Date: 4/15/16
 * Time: 1:18 PM
 *  @var $this FormController
 *  @var $model SearchForm
 *  @var $colorSchemeAttributes array
 *  @var $colorSchemeAttribute ColorSchemeAttribute
 */
?>
<div class="col-xs-12 form-container">


    <!--FORM PREVIEW START-->
    <?=$this->renderPartial("_form-preview", ["model" => $model])?>
    <!--FORM PREVIEW END-->

    <!--SEPARATOR-->
    <div class="clearfix">&nbsp;</div>

    <?= CHtml::beginForm();?>

    <!--ERRORS DISPLAY-->
    <?= CHtml::errorSummary($model);?>

    <!--SETTINGS START-->
    <div class="panel-group" id="" role="tablist" aria-multiselectable="true">

        <!--DESIGN START-->
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingDesign">
                <h4 class="panel-title">
                    <a role="button" onclick="$(this).find('i').toggleClass('glyphicon-triangle-bottom').toggleClass('glyphicon-triangle-top')" data-toggle="collapse" href="#collapseDesign" aria-expanded="true" aria-controls="collapseDesign" class="text-decoration-none">
                        <p class="margin-0">Design settings
                            <i class="glyphicon glyphicon-triangle-top float-right"></i>
                        </p>
                    </a>
                </h4>
            </div>
            <div id="collapseDesign" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingDesign">
                <div class="panel-body">
                    <!--WIDTH START-->
                    <div class="col-xs-12">
                        <?=CHtml::activeLabel($model, "width");?>
                        <?=CHtml::activeNumberField($model, "width", ["id" => "formWidth", "onchange" => 'setFormWidth(this.value)', "class" => ($model->is100per ? " display-none ": "display-block")]);?>
                        <?=CHtml::activeCheckBox($model, "is100per", ["onchange" => '$(this).parent().find("#formWidth").toggleClass("display-none"); if(this.checked){setFormWidth("100%");}']);?>
                        <?=CHtml::activeLabel($model, "is100per");?>
                    </div>
                    <!--WIDTH END-->

                    <!--SEPARATOR-->
                    <div class="clearfix">&nbsp;</div>

                    <!--COLOR SCHEME START-->
                    <div class="col-xs-12">
                        <div class="color-scheme-container">
                            <?php
                                foreach($colorSchemeAttributes as $k=>$colorSchemeAttribute){
                                    $colorSchemeAttribute->value = $model->{$colorSchemeAttribute->inputName};
                                    echo CHtml::activeHiddenField($model, $k,["id" => $k."Input"]);
                                }
                            ?>

                            <!--INITIAL COLOR SCHEME-->
                            <input type="hidden" class="initialColorScheme" onclick="changeScheme(<?=str_replace('"', '\'', json_encode($colorSchemeAttributes))?>)">


                            <!--COLOR SCHEMES-->
                            <?=$this->renderPartial("_color-schemes",["colorSchemeAttributes" => $colorSchemeAttributes])?>

                            <!--CUSTOM COLOR SCHEME-->
                            <div class="color-scheme-icon position-relative">
                                <div class="height-100per" onclick="$(this).parent().find('.custom-scheme').toggleClass('display-none');$('.color-scheme-icon').removeClass('active'); $(this).parent().addClass('active'); event.stopPropagation();">
                                    <div class="custom-scheme-label"><span>Custom scheme</span></div>
                                </div>

                                <?=$this->renderPartial("_custom-color-scheme",['model' => $model, "colorSchemeAttributes" => $colorSchemeAttributes])?>
                            </div>

                        </div>
                    </div>
                    <!--COLOR SCHEME END-->
                </div>
            </div>
        </div>
        <!--DESIGN END-->

        <!--OUTPUT SETTINGS START-->
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOutput">
                <h4 class="panel-title">
                    <a role="button" onclick="$(this).find('i').toggleClass('glyphicon-triangle-bottom').toggleClass('glyphicon-triangle-top')" data-toggle="collapse" href="#collapseOutput" aria-expanded="true" aria-controls="collapseOutput" class="text-decoration-none">
                        <p class="margin-0">Output settings
                            <i class="glyphicon glyphicon-triangle-bottom float-right"></i>
                        </p>
                    </a>
                </h4>
            </div>
            <div id="collapseOutput" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOutput">
                <div class="panel-body">
                    <div class="">
                        <div class="row">
                            <div class="col-sm-6">
                                <?=CHtml::activeLabel($model, "title");?>
                                <?=CHtml::activeTextField($model, "title", ['class' => "form-control"]);?>
                            </div>
                            <div class="col-sm-3">
                                <?=CHtml::activeLabel($model, "defaultOrigin");?>
                                <?=CHtml::activeTextField($model, "defaultOrigin", ['class' => "form-control"]);?>
                            </div>
                            <div class="col-sm-3">
                                <?=CHtml::activeLabel($model, "defaultDestination");?>
                                <?=CHtml::activeTextField($model, "defaultDestination", ['class' => "form-control"]);?>
                            </div>
                        </div>

                        <div class="clearfix">&nbsp;</div>

                        <div class="row">
                            <div class="col-sm-4">
                                <?=CHtml::activeLabel($model, "language");?>
                                <?=CHtml::activeDropDownList($model, "language", ['en' => "English", 'ru' => 'Russian'], ['class' => 'form-control']);?>
                            </div>
                            <div class="col-sm-4">
                                <?=CHtml::activeLabel($model, "currency");?>
                                <?=CHtml::activeDropDownList($model, "currency", [
                                    'USD' => "USD",
                                    'EUR' => "EUR",
                                    'GBP' => "GBP",
                                    'RUB' => "RUB",
                                    'UAH' => "UAH",
                                    'CNY' => "CNY",
                                ], ['class' => 'form-control']);?>
                            </div>

                            <div class="col-sm-4">
                                <?=CHtml::activeLabel($model, "target");?>
                                <?=CHtml::activeDropDownList($model, "target", ['_blank' => "Open in new window or tab", '_self' => 'Open in the same frame'], ['class' => 'form-control']);?>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!--OUTPUT SETTINGS END-->
    </div>
    <!--SETTINGS END-->

    <!--SAVE BUTTON-->
    <div class="col-xs-12 padding-0">
        <?=CHtml::submitButton("Save the form and get the cod", ["class" => "btn-sm border-radius-0 btn-info btn", "name" => "submit"]);?>
    </div>

    <!--SEPARATOR-->
    <div class="clearfix">&nbsp;</div>

    <!--CODE TEXT AREA-->
    <div class="col-xs-12 padding-0 position-relative">
        <textarea class="col-xs-12 code-container"></textarea>
        <button onclick="copyToClipboard($(this).parent().find('.code-container')); return false;" class="border-radius-0 right-30 position-absolute btn btn-default btn-xs">Select all</button>
        <script type="text/javascript">
            $(document).ready(function(){
                getSearchFormCode(<?=$model->id?>, "textarea")
            });
        </script>
    </div>


    <?= CHtml::endForm();?>
</div>

protected/views/form/create.php
<?php
/**
 * Created by PhpStorm.
 * User: A&A
 * Date: 4/15/16
 * Time: 1:18 PM
 *
 *  @var $this FormController
 *  @var $model SearchForm
 *  @var $colorSchemeAttributes array
 */
$this->breadcrumbs=array(
	'Create Form',
);

$this->renderPartial("_form",[
    "model" => $model,
    "colorSchemeAttributes" => $colorSchemeAttributes
])
?>

protected/views/form/index.php
<?php
/* @var $this FormController */
/* @var $models array */
/* @var $model UserForm */

$this->breadcrumbs=array(
	'My Forms',
);
?>

<div id="getCodeModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content border-radius-0">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Copy this code to your web page</h4>
            </div>
            <div class="modal-body">
                <textarea class="col-xs-12 code-container"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn-sm border-radius-0 btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" onclick="copyToClipboard($(this).parent().parent().find('.code-container'))" class="btn-sm border-radius-0 btn btn-primary">Select all</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="row">
    <table class="col-xs-12 table table-responsive">
        <thead>
        <th>Title</th>
        <th>Language</th>
        <th>Currency</th>
        <th><!--controls--></th>
        </thead>
        <tbody>
            <?php foreach($models as $model):
                $data = json_decode($model->data, true);
                ?>
                <tr>
                    <td>
                        <p style="
                            color: <?=$data["colorSchemeText"]?>;
                            border: 1px solid <?=$data["colorSchemeBorder"]?>;
                            background: <?=$data["colorSchemeBackground"]?>;
                            padding: 7px;
                            margin: 0;
                            ">
                            <?=$model->title?>
                            <i style="color: <?=$data["colorSchemeIcon"]?>; background: #fff;" class="glyphicon glyphicon-plane float-right padding-2"></i>
                        </p>
                    </td>
                    <td><?=$data["language"]?></td>
                    <td><?=$data["currency"]?></td>
                    <td>
                        <button class="btn btn-default border-radius-0 margin-0-5" onclick="getSearchFormCode(<?=$model->id?>, 'modal')">Get code</button>
                        <?=CHtml::link("Edit", ["/form/update", "id" => $model->id], ["class"=>"btn btn-default border-radius-0 margin-0-5"])?>
                        <?=CHtml::link("Delete", ["/form/delete", "id" => $model->id], ["class"=>"btn btn-danger border-radius-0 margin-0-5", 'confirm' => 'Are you sure?'])?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>

    <div class="col-xs-12">
        <a href="<?=$this->createUrl("/form/create",[])?>">
            <button class="btn-lg border-radius-0 btn-info btn"> + Create a new form </button>
        </a>
    </div>
</div>

protected/views/form/update.php
<?php
/**
 * Created by PhpStorm.
 * User: A&A
 * Date: 4/15/16
 * Time: 1:18 PM
 *  @var $this FormController *
 * @var $model SearchForm
 * @var $colorSchemeAttributes array
 */
$this->breadcrumbs=array(
    'Update Form',
);

$this->renderPartial("_form",[
    "model" => $model,
    "colorSchemeAttributes" => $colorSchemeAttributes
])
?>